### Register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### Login check
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzAzMDk0MCwiZXhwIjoxNzc3MDMxNTQwfQ.Bua2fNd_ez6IgKRgKHuR5CS02mmgUxb5NccgDHtEit0

### get account check
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzE4MTk3MiwiZXhwIjoxNzc3MTgyNTcyfQ.O2QIET8fyEejf1TXzK0GwEa8m1s4NzrGNeo9Jbeq64I

### refresh token
POST  http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### change password
PATCH http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njc3NjE3NCwiZXhwIjoxNzc2Nzc2Nzc0fQ.-vaZrehTK8YLo52nEogbheJ_1dLq58Zk8Wbr3Brj2rQ
Content-Type: application/json

{
    "password": "P@ssw0rd123"
}

### update account
PATCH http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzAzMDk0MCwiZXhwIjoxNzc3MDMxNTQwfQ.Bua2fNd_ez6IgKRgKHuR5CS02mmgUxb5NccgDHtEit0
Content-Type: application/json

{
    "bio": "hello i am good"
}

### forget password
POST http://localhost:3000/api/auth/forget-password
Content-Type: application/json

{
    "email":"sumi123@gmail.com"
}

### reset password
POST http://localhost:3000/api/auth/reset-password?token=814cc3cf7fcaf4624834af80b864f0aa
Content-Type: application/json

{
    "password": "P@ssw0rd"
}

### verify email
POST http://localhost:3000/api/auth/verify-email?token=814cc3cf7fcaf4624834af80b864f0aa
Content-Type: application/json

{}