### Register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### Login check
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzYyNzYyMCwiZXhwIjoxNzc3NjI4MjIwfQ.fcLC4LO6_n4fB80YfZGu-BpcoSoVIdSLa0Ll1de0F5M

### get account check
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc3Nzc5ODAwNSwiZXhwIjoxNzc3Nzk4NjA1fQ.MvrtohJhHtUic55oruVey4PHN8DEdwfOiWshJUqUQ-s

### refresh token
POST  http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### change password
PATCH http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njc3NjE3NCwiZXhwIjoxNzc2Nzc2Nzc0fQ.-vaZrehTK8YLo52nEogbheJ_1dLq58Zk8Wbr3Brj2rQ
Content-Type: application/json

{
    "password": "P@ssw0rd123"
}

### update account
PATCH http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzAzMDk0MCwiZXhwIjoxNzc3MDMxNTQwfQ.Bua2fNd_ez6IgKRgKHuR5CS02mmgUxb5NccgDHtEit0
Content-Type: application/json

{
    "bio": "hello i am good"
}

### forget password
POST http://localhost:3000/api/auth/forget-password
Content-Type: application/json

{
    "email":"sumi123@gmail.com"
}

### reset password
POST http://localhost:3000/api/auth/reset-password?token=814cc3cf7fcaf4624834af80b864f0aa
Content-Type: application/json

{
    "password": "P@ssw0rd"
}

### verify email
POST http://localhost:3000/api/auth/verify-email?token=2780ef842695331b7a5b78bb9c6fa9d3
Content-Type: application/json

{}

### Register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"mohan",
    "email":"mohan123@gmail.com",
    "password":"P@ssw0rd123",
    "bio": "i am a developer"
}

### Login check
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"mohan123@gmail.com",
    "password":"P@ssw0rd123"
}