### Register new user
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "name":"sumila",
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd"
}

### Login check
POST  http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"sumi123@gmail.com",
    "password":"P@ssw0rd123"
}

### logout check
POST http://localhost:3000/api/auth/logout
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njc1NjEzOSwiZXhwIjoxNzc2NzU2NzM5fQ.WCOw-26KTJLcayQ1hna4aKLo-8CHHPwHuqJQv3Fle9s

### get account check
GET http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njg0NzkxMywiZXhwIjoxNzc2ODQ4NTEzfQ.Q76dlHFTebbERCrmuT9zFKxJbnhfTImQyXdxtIsTh4M

### refresh token
POST  http://localhost:3000/api/auth/refresh
Content-Type: application/json

{}

### change password
PATCH http://localhost:3000/api/auth/change-password
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njc3NjE3NCwiZXhwIjoxNzc2Nzc2Nzc0fQ.-vaZrehTK8YLo52nEogbheJ_1dLq58Zk8Wbr3Brj2rQ
Content-Type: application/json

{
    "password": "P@ssw0rd123"
}

### update account
PATCH http://localhost:3000/api/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Njg0NzkxMywiZXhwIjoxNzc2ODQ4NTEzfQ.Q76dlHFTebbERCrmuT9zFKxJbnhfTImQyXdxtIsTh4M
Content-Type: application/json

{
    "bio": "hello i am good"
}