### send invitation
POST http://localhost:3000/api/teams/1/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc4Mjg5Mzc5OSwiZXhwIjoxNzgyODk0Mzk5fQ.uq0LPt38AIH6r7L-stOKBD_3uONy5v04QAhJym9HWGU
Content-Type: application/json

{
    "inviteeId": 2
}

### get all invitations
GET http://localhost:3000/api/invitations?invitationStatus=rejected
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4Mjg5Mzg0MiwiZXhwIjoxNzgyODk0NDQyfQ.TD9pfDtAFVn2HZ12CVdpJmq3Zbvey-omtI1fl2clwqQ

### process invitations
PATCH http://localhost:3000/api/invitations/1/process
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjIsImlhdCI6MTc4Mjg5Mzg0MiwiZXhwIjoxNzgyODk0NDQyfQ.TD9pfDtAFVn2HZ12CVdpJmq3Zbvey-omtI1fl2clwqQ
Content-Type: application/json

{
    "token": "5c3046436fb1e1f0da0baba80b0f119e",
    "action": "accepted"
}