### create team 
POST http://localhost:3000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzYyNzMyNSwiZXhwIjoxNzc3NjI3OTI1fQ.FUBlOo1YHq-zE3EJafV3QkyS-oHEkTML4u5M__FHvZI
Content-Type: application/json

{
    "teamName": "test",
    "description": "this team is to test the code"
}

### get all the users team
GET http://localhost:3000/api/teams
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzYyNzMyNSwiZXhwIjoxNzc3NjI3OTI1fQ.FUBlOo1YHq-zE3EJafV3QkyS-oHEkTML4u5M__FHvZI

### get team by id
GET http://localhost:3000/api/teams/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzYyNjI3NSwiZXhwIjoxNzc3NjI2ODc1fQ.sQPGig4NFc-Pbd1LohhA5Yv7ACWRlOkII6ct6q087Kc

### update team
PATCH http://localhost:3000/api/teams/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzM4NDQ2MiwiZXhwIjoxNzc3Mzg1MDYyfQ.Boia7hcgpYDvLIR1VdkIpDduYZamNTz9lxO-fd7kP88
Content-Type: application/json

{}

### delete team
DELETE http://localhost:3000/api/teams/2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzM4NDQ2MiwiZXhwIjoxNzc3Mzg1MDYyfQ.Boia7hcgpYDvLIR1VdkIpDduYZamNTz9lxO-fd7kP88

### get all team members
GET http://localhost:3000/api/teams/1/members
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Nzk2NTY5NCwiZXhwIjoxNzc3OTY2Mjk0fQ.Bjk3OYO4w4nTfrGhRhdBClmUTwawvcIlHqKz4nI3B2M

### send invitation
POST http://localhost:3000/api/teams/1/invite
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3NzYyNzYyMCwiZXhwIjoxNzc3NjI4MjIwfQ.fcLC4LO6_n4fB80YfZGu-BpcoSoVIdSLa0Ll1de0F5M
Content-Type: application/json

{
    "inviteeId": 2
}

### update team member
PATCH http://localhost:3000/api/teams/1/members/2/role
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Nzc4MDQ5NSwiZXhwIjoxNzc3NzgxMDk1fQ.fg0kgnjvkFHCPuHchjc0javawSeyMdLTvqprlXDWBzU
Content-Type: application/json

{
    "role": "team_leader"
}

### remove team member
DELETE http://localhost:3000/api/teams/1/members/4
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOjEsImlhdCI6MTc3Nzc4MDQ5NSwiZXhwIjoxNzc3NzgxMDk1fQ.fg0kgnjvkFHCPuHchjc0javawSeyMdLTvqprlXDWBzU